version: '3.9'

services:
  
  # The app should be run locally

  # Reference: https://hub.docker.com/_/postgres
  db:
    image: postgres:16
    restart: always
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: razor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example